# Send us messages on slack when users from the community either open new issues or PRs
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  notify_slack:
    name: Notify team
    runs-on: ubuntu-latest
    steps:
      - name: Check if it's team member
        id: is_team_member
        if: github.event.action == 'opened'
        uses: mathnogueira/user-blocklist@1.0.0
        with:
          blocked_users: adnanrahic, danielbdias, jfermi, jorgeepc, kdhamric, olha23, schoren, xoscar

      - name: Label issue
        if: |
          steps.is_team_member.outputs.result == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['user-request']
            })

      - name: Notify us if not a kubeshop member
        if: |
          steps.is_team_member.outputs.result == 'false'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: tracetest
          SLACK_COLOR: good
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_TITLE: An issue was opened by a user
          SLACK_MESSAGE: ${{ github.event.issue.title }}
          SLACK_USERNAME: GitHub
          SLACK_LINK_NAMES: true
          SLACK_FOOTER: ${{ github.event.issue.html_url }}
          MSG_MINIMAL: true
